### PR TITLE
VA-Sensor | Emulator | MainService

### LINKED ISSUE #13: Back | VA-Sensor | Emulator | MainService
- [x] Implementation bases on the  [template](https://github.com/a-givertzman/rust-sal-sync/blob/master/src/services/service/service_template.rs)
- [x] Executed in the separated thread
- [x] Number of UDP messages per second determines by sampl_freq & bus_size
- [x] Transmit cycle implemented using [ServiceCycle](https://github.com/a-givertzman/rust-sal-sync/blob/master/src/services/service/service_cycle.rs)
- [x] UDP Bind implemented in the separate method
- [x] UDP message described [here](https://github.com/a-givertzman/cma-server/issues/123)
- [ ] Integration test
   ```rust
   /// 
   /// Test MainService
   let target_count = 3;
   let main_service = Arc::new(Mutex::new(MainService::new(...)))
   match main_service.clone().lock().unwrap().run() {
      Ok => {
         let client = UdpSocket::new(server_ip);
         tread.spawn(move || {
            while received < target_count {
               match client.recv() {
                  Ok(bytes) => {
                     match bytes {
                        // match bytes
                        // ...
                        _ => panic!("Incorrect message", bytes);
                     }
                  }
                  Err(err) => {
                     panic!("SOcet error: {}", err);
                  }
               }
            }
            main_service.clone().lock().unwrap().exit();
         })
      }
      Err(err) => {
         panic!("...", err);
      }
   }
   ```

### PR DESCRIPTION
**Pull request by pivovarvalera**

### CODE REVIEW

File: src/main_service/main_service.rs [hunk 1]
```diff
@@ -9,31 +9,70 @@ use sal_sync::services::{conf::conf_tree::ConfTree, entity::{
...
+        Self{
+            syn,
+            addr,
+            r#type,
+            count,
+        }
+    }
+    //
+    /// Convert fields of UdpHeader to Vector
+    pub fn header_to_bytes(&self) -> Vec<u8>{
```
Comment (a-givertzman) [inline src/main_service/main_service.rs:34]: 'to_bytes()' - will be nice

File: src/main_service/main_service.rs [hunk 2]
```diff
@@ -9,31 +9,70 @@ use sal_sync::services::{conf::conf_tree::ConfTree, entity::{
...
+        let mut header_bytes = Vec::with_capacity(4);
+        header_bytes.push(self.syn);
+        header_bytes.push(self.addr);
+        header_bytes.push(self.r#type);
+        header_bytes.push(self.count);
+
```
Comment (a-givertzman) [inline src/main_service/main_service.rs:40]: empty lines is not required

File: src/main_service/main_service.rs [hunk 3]
```diff
@@ -9,31 +9,70 @@ use sal_sync::services::{conf::conf_tree::ConfTree, entity::{
...
+    /// Creates a message for udp
+    pub fn new(header: UdpHeader, data: Vec<u8>) -> Self{
+        Self{
+            header,
+            data,
+        }
+    }
+    //
+    /// Convert fields of UdpMessage to Vector
+    pub fn message_to_bytes(&self) -> Vec<u8>{
```
Comment (a-givertzman) [inline src/main_service/main_service.rs:63]: 'message()' - can be used

File: src/main_service/main_service.rs [hunk 4]
```diff
@@ -9,31 +9,70 @@ use sal_sync::services::{conf::conf_tree::ConfTree, entity::{
...
+        }
+
+        for &bytes in &self.data{
+            message_bytes.push(bytes);
+        }
+
+        message_bytes
+    }
 }
 pub struct MainService{
```
Comment (a-givertzman) [inline src/main_service/main_service.rs:77]: Doc comment required

File: src/main_service/main_service.rs [hunk 5]
```diff
@@ -9,31 +9,70 @@ use sal_sync::services::{conf::conf_tree::ConfTree, entity::{
...
-//         let phi = conf["phi"].as_i64().unwrap_or(0.0) as f64;
-//         Self{
-//             ampl,
-//             phi,
-//         }
-//     }
-// }
-//
-//
 pub struct UdpHeader {
```
Comment (a-givertzman) [inline src/main_service/main_service.rs:15]: Doc comment required

File: src/main_service/main_service.rs [hunk 6]
```diff
@@ -9,31 +9,70 @@ use sal_sync::services::{conf::conf_tree::ConfTree, entity::{
...
     pub syn: u8,
     pub addr: u8,
     pub r#type: u8,
     pub count: u8,
-    pub data: [u8; 1024],
+}
+impl UdpHeader{
```
Comment (a-givertzman) [inline src/main_service/main_service.rs:21]: ↑ prefer in style convenient 
//
//

File: src/main_service/main_service.rs [hunk 7]
```diff
@@ -106,44 +145,47 @@ impl Service for MainService {
...
-            let parent = "";
-            let conf_tree = ConfTree::new();
-            let config = MainService::new(parent, conf_tree);
-            for(freq, amp, phi) in config.signal{
-                let amplitude = amp;
-                let angle = phi;
-            }
-            let buf:[u8; 0] = [];
-            //let header = todo!("Udp message head, find detales here: https://github.com/a-givertzman/cma-server/issues/123#issue-2478437558");
+            let config = MainService::new(&dbg_id, conf_tree);
```
Comment (a-givertzman) [inline src/main_service/main_service.rs:158]: What does it mean?
We are already inside `MainService` which is `&mut self` isn't it?

File: src/main_service/main_service.rs [hunk 8]
```diff
@@ -106,44 +145,47 @@ impl Service for MainService {
...
-                            let amp_bytes = amp.to_be_bytes();
-                        });
-                        socket.send(bytes);
-                        cycle.wait();
+
+                for (freq, amp, phi) in config.conf.signal.iter(){
+                    let amplitude = amp;
+                    buf.push(amplitude);
+
+                    if (buf.capacity() == buf.len()){
```
Comment (a-givertzman) [inline src/main_service/main_service.rs:167]: I thought `src/buffer.rs` - was implemented exactly for accumulating with specified capacity like:
```rust
match buf.add(amplitude) {
   Some() => {
      ...
   }
   None -> {
      ...
   }
}
```

File: src/main_service/main_service.rs [hunk 9]
```diff
@@ -106,44 +145,47 @@ impl Service for MainService {
...
+
+                        match Self::udp_bind(addr){
+                            Ok(socket) => {
+                                cycle.start();
+                                let header = UdpHeader::new(0, 0, 32, 255);
+
+                                let bytes: &[u8] = unsafe {
```
Comment (a-givertzman) [inline src/main_service/main_service.rs:174]: try to avoid unsafe

**Review by a-givertzman — CHANGES_REQUESTED** [review]

File: src/main_service/main_service.rs [hunk 10]
```diff
@@ -1,48 +1,101 @@
...
 pub struct UdpHeader {
     pub syn: u8,
     pub addr: u8,
     pub r#type: u8,
     pub count: u8,
-    pub data: [u8; 1024],
 }
+//
+//
+impl UdpHeader{
```
Comment (a-givertzman) [inline src/main_service/main_service.rs:28]: Move to the `udp_header.rs` file
- develop in the Issie-PR pair
- may bee unit test ?

File: src/main_service/main_service.rs [hunk 11]
```diff
@@ -1,48 +1,101 @@
...
+        header_bytes.push(self.r#type);
+        header_bytes.push(self.count);
+        header_bytes
+    }
+}
+///
+/// Struct `UpdMessage`
+/// - `header` - contains the UPD header information
+/// - `data` - array of values
+pub struct UpdMessage{
```
Comment (a-givertzman) [inline src/main_service/main_service.rs:54]: Move to the `udp_message.rs` file
- develop in the Issie-PR pair
- may bee unit test ?

File: src/main_service/main_service.rs [hunk 12]
```diff
@@ -107,43 +160,42 @@ impl Service for MainService {
         info!("{}.run | Starting...", self.dbg_id);
         let dbg_id = self.dbg_id.clone();
         let exit = self.exit.clone();
+        let conf = self.conf.clone();
         info!("{}.run | Preparing thread...", dbg_id);
+
```
Comment (a-givertzman) [inline src/main_service/main_service.rs:165]: avoid empty lines in the code block

File: src/main_service/main_service.rs [hunk 13]
```diff
@@ -107,43 +160,42 @@ impl Service for MainService {
...
-                        socket.send(bytes);
-                        cycle.wait();
+                for (freq, amp, phi) in conf.signal.iter(){
+                    let amplitude = amp;
+                    match buf.add(*amplitude){
+                        Some(_) =>{
+                            match Self::udp_bind(addr){
+                                Ok(socket) => {
+                                    cycle.start();
+                                    let header = UdpHeader::new(0, 0, 32, 255);
```
Comment (a-givertzman) [inline src/main_service/main_service.rs:181]: Replace literals with constants, defined in the responsible classes if possible.

File: src/main_service/main_service.rs [hunk 14]
```diff
@@ -1,48 +1,101 @@
...
+            syn,
+            addr,
+            r#type,
+            count,
+        }
+    }
+    ///
+    /// Convert fields of UdpHeader to Vector
+    pub fn to_bytes(&self) -> Vec<u8>{
+        let mut header_bytes = Vec::with_capacity(4);
```
Comment (a-givertzman) [inline src/main_service/main_service.rs:42]: replace literal with SYN = 4, defined in the responsible class

File: src/main_service/main_service.rs [hunk 15]
```diff
@@ -107,43 +160,42 @@ impl Service for MainService {
...
+                                Ok(socket) => {
+                                    cycle.start();
+                                    let header = UdpHeader::new(0, 0, 32, 255);
+                                    let buf_i16 = buf.array.clone();
+                                    let bytes = buf_i16.iter().flat_map(|&byte|byte.to_ne_bytes()).collect();
+    
+                                    let message = UpdMessage::new(header, bytes);
+    
+                                    // &[u8]
+                                    socket.send(&message.message()).expect("Failed to send message");
```
Comment (a-givertzman) [inline src/main_service/main_service.rs:188]: match send result,
just log if error for now

**Review by a-givertzman — CHANGES_REQUESTED** [review]
